'use client'

import { Inter } from 'next/font/google'
import './globals.css'
import Header from '../../components/Header/Header'


import { Provider } from 'react-redux'
import { store } from '../../components/store/Store'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <Provider store={store}>

          <Header />
          <body className={inter.className}>{children}</body>
        </Provider >
      </html>
    </>
  )
}
